services:
  front:
    container_name: shortener-front-dev
    image: shortener-front-dev
    build:
      context: ./front
      dockerfile: dev.Dockerfile 
    volumes:
      - ./front/:/app
      - /app/node_modules
    ports:
      - 3000:3000
    env_file: ./front/.env.local

  back:
    container_name: shortener-back-dev
    image: shortener-back-dev
    build:
      context: ./api
      dockerfile: dev.Dockerfile
    env_file: ./api/.env
    volumes:
      - ./api:/app
    ports:
      - 3001:3001

  # mongo:
  #   image: mongo
  #   ports:
  #     - 3456:27017
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #     MONGO_INITDB_DATABASE: the_database 
  #   volumes: 
  #     - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
  #     - ./todo-backend/mongo_data:/data/db

